version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-serverless-webapp"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1aw13szo2dxwl"
s3_prefix = "sam-serverless-webapp"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
